In [1]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv('test.csv')

In [4]:
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [5]:
df = pd.DataFrame(data)

In [6]:
print(df)

        Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg
1     1462          20       RL         81.0    14267   Pave   NaN      IR1
2     1463          60       RL         74.0    13830   Pave   NaN      IR1
3     1464          60       RL         78.0     9978   Pave   NaN      IR1
4     1465         120       RL         43.0     5005   Pave   NaN      IR1
...    ...         ...      ...          ...      ...    ...   ...      ...
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg

     LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence  \
0            Lvl    AllPub  ...         120        0    NaN  MnPrv
1            Lvl    AllPub  ...           0        0    NaN    NaN
2            Lvl    AllPub  ...           0        0    NaN  MnPrv
3            Lvl    AllPub  ...           0        0    NaN    NaN
4            HLS    AllPub  ...         144        0    NaN    NaN
...          ...       ...  ...         ...      ...    ...    ...
1454         Lvl    AllPub  ...           0        0    NaN    NaN
1455         Lvl    AllPub  ...           0        0    NaN    NaN
1456         Lvl    AllPub  ...           0        0    NaN    NaN
1457         Lvl    AllPub  ...           0        0    NaN  MnPrv
1458         Lvl    AllPub  ...           0        0    NaN    NaN

     MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition
0            NaN       0      6    2010        WD         Normal
1           Gar2   12500      6    2010        WD         Normal
2            NaN       0      3    2010        WD         Normal
3            NaN       0      6    2010        WD         Normal
4            NaN       0      1    2010        WD         Normal
...          ...     ...    ...     ...       ...            ...
1454         NaN       0      6    2006        WD         Normal
1455         NaN       0      4    2006        WD        Abnorml
1456         NaN       0      9    2006        WD        Abnorml
1457        Shed     700      7    2006        WD         Normal
1458         NaN       0     11    2006        WD         Normal

[1459 rows x 80 columns]

In [10]:
for column_name, data_type in data.dtypes.items():
    print(f"Column Name: {column_name}, Data Type: {data_type}")

Column Name: Id, Data Type: int64
Column Name: MSSubClass, Data Type: int64
Column Name: MSZoning, Data Type: object
Column Name: LotFrontage, Data Type: float64
Column Name: LotArea, Data Type: int64
Column Name: Street, Data Type: object
Column Name: Alley, Data Type: object
Column Name: LotShape, Data Type: object
Column Name: LandContour, Data Type: object
Column Name: Utilities, Data Type: object
Column Name: LotConfig, Data Type: object
Column Name: LandSlope, Data Type: object
Column Name: Neighborhood, Data Type: object
Column Name: Condition1, Data Type: object
Column Name: Condition2, Data Type: object
Column Name: BldgType, Data Type: object
Column Name: HouseStyle, Data Type: object
Column Name: OverallQual, Data Type: int64
Column Name: OverallCond, Data Type: int64
Column Name: YearBuilt, Data Type: int64
Column Name: YearRemodAdd, Data Type: int64
Column Name: RoofStyle, Data Type: object
Column Name: RoofMatl, Data Type: object
Column Name: Exterior1st, Data Type: object
Column Name: Exterior2nd, Data Type: object
Column Name: MasVnrType, Data Type: object
Column Name: MasVnrArea, Data Type: float64
Column Name: ExterQual, Data Type: object
Column Name: ExterCond, Data Type: object
Column Name: Foundation, Data Type: object
Column Name: BsmtQual, Data Type: object
Column Name: BsmtCond, Data Type: object
Column Name: BsmtExposure, Data Type: object
Column Name: BsmtFinType1, Data Type: object
Column Name: BsmtFinSF1, Data Type: float64
Column Name: BsmtFinType2, Data Type: object
Column Name: BsmtFinSF2, Data Type: float64
Column Name: BsmtUnfSF, Data Type: float64
Column Name: TotalBsmtSF, Data Type: float64
Column Name: Heating, Data Type: object
Column Name: HeatingQC, Data Type: object
Column Name: CentralAir, Data Type: object
Column Name: Electrical, Data Type: object
Column Name: 1stFlrSF, Data Type: int64
Column Name: 2ndFlrSF, Data Type: int64
Column Name: LowQualFinSF, Data Type: int64
Column Name: GrLivArea, Data Type: int64
Column Name: BsmtFullBath, Data Type: float64
Column Name: BsmtHalfBath, Data Type: float64
Column Name: FullBath, Data Type: int64
Column Name: HalfBath, Data Type: int64
Column Name: BedroomAbvGr, Data Type: int64
Column Name: KitchenAbvGr, Data Type: int64
Column Name: KitchenQual, Data Type: object
Column Name: TotRmsAbvGrd, Data Type: int64
Column Name: Functional, Data Type: object
Column Name: Fireplaces, Data Type: int64
Column Name: FireplaceQu, Data Type: object
Column Name: GarageType, Data Type: object
Column Name: GarageYrBlt, Data Type: float64
Column Name: GarageFinish, Data Type: object
Column Name: GarageCars, Data Type: float64
Column Name: GarageArea, Data Type: float64
Column Name: GarageQual, Data Type: object
Column Name: GarageCond, Data Type: object
Column Name: PavedDrive, Data Type: object
Column Name: WoodDeckSF, Data Type: int64
Column Name: OpenPorchSF, Data Type: int64
Column Name: EnclosedPorch, Data Type: int64
Column Name: 3SsnPorch, Data Type: int64
Column Name: ScreenPorch, Data Type: int64
Column Name: PoolArea, Data Type: int64
Column Name: PoolQC, Data Type: object
Column Name: Fence, Data Type: object
Column Name: MiscFeature, Data Type: object
Column Name: MiscVal, Data Type: int64
Column Name: MoSold, Data Type: int64
Column Name: YrSold, Data Type: int64
Column Name: SaleType, Data Type: object
Column Name: SaleCondition, Data Type: object

In [11]:
data.to_csv('data.csv')